# El método de los k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30, 3)
data

array([[0.46913161, 0.96814725, 0.64170499],
       [0.41250751, 0.67231842, 0.24007729],
       [0.4151545 , 0.11201409, 0.07963906],
       [0.82790728, 0.22163087, 0.16303246],
       [0.28292193, 0.07160548, 0.28742045],
       [0.50795093, 0.92767662, 0.09819306],
       [0.76991199, 0.87136138, 0.28319148],
       [0.50085597, 0.58474691, 0.03147503],
       [0.70321926, 0.22778412, 0.4702668 ],
       [0.44428989, 0.31130396, 0.71793422],
       [0.83362783, 0.93663405, 0.60309139],
       [0.33331575, 0.7198984 , 0.6915373 ],
       [0.49742493, 0.89719868, 0.0331982 ],
       [0.5198044 , 0.44017083, 0.91137483],
       [0.38408607, 0.13695804, 0.1686455 ],
       [0.8564163 , 0.65114665, 0.65241778],
       [0.70507582, 0.12808225, 0.77205879],
       [0.84480871, 0.6674376 , 0.02179668],
       [0.84699531, 0.04931438, 0.07906187],
       [0.74467739, 0.27810503, 0.55884998],
       [0.36516921, 0.60178299, 0.70478622],
       [0.04015461, 0.51279079, 0.23644342],
       [0.

In [4]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.70507582, 0.12808225, 0.77205879],
       [0.94023185, 0.28207551, 0.7543758 ]])

In [5]:
from scipy.cluster.vq import vq

In [6]:
vq(data, clust_centers)

(array([1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 0], dtype=int32),
 array([0.83983605, 0.81534872, 0.75083796, 0.60494405, 0.64519597,
        1.01697756, 0.77348649, 0.89370726, 0.31784008, 0.32327847,
        0.68021929, 0.70351661, 1.04620821, 0.38875923, 0.68353551,
        0.39196172, 0.        , 0.83323567, 0.71175153, 0.26369132,
        0.58690246, 0.93648529, 0.        , 0.76472395, 0.89683835,
        0.39178856, 0.75736306, 0.838442  , 0.63517325, 0.63928476]))

In [7]:
from scipy.cluster.vq import kmeans

In [8]:
kmeans(data, clust_centers)

(array([[0.53235902, 0.24256122, 0.3955596 ],
        [0.54795033, 0.76902722, 0.37221609]]), 0.3790441046505143)

In [9]:
kmeans(data, 2)

(array([[0.4848182 , 0.39891067, 0.13214676],
        [0.5934123 , 0.5424823 , 0.63874139]]), 0.3713458023097239)